import assert from 'node:assert/strict';
import {newGame,act,ai,card,starter,stats} from '../lib/game.ts';
const make=(id,extra={})=>({id,uid:crypto.randomUUID(),sick:false,tapped:false,damage:0,boost:0,...extra});
const fresh=()=>newGame('Warrior');
const passes=g=>{act(g,g.priority,{type:'pass'});act(g,g.priority,{type:'pass'});};
let g=fresh();g.players[0].hand=['plains','plains','guard'];act(g,0,{type:'play',index:0});assert.throws(()=>act(g,0,{type:'play',index:0}));act(g,0,{type:'tap',uid:g.players[0].lands[0].uid});assert.equal(g.players[0].pool.W,1);act(g,0,{type:'play',index:1});assert.equal(g.stack.length,1);assert.equal(g.players[0].board.length,0);passes(g);assert.equal(g.players[0].board[0].id,'guard');assert.equal(g.players[0].pool.W,0);
g=fresh();g.players[0].lands=[make('swamp')];g.players[0].hand=['guard'];assert.throws(()=>act(g,0,{type:'play',index:0}));
g=fresh();g.players[0].hand=['guard'];g.players[0].lands=[make('plains')];g.players[1].hand=['deny'];g.players[1].lands=[make('swamp'),make('swamp')];act(g,0,{type:'play',index:0});act(g,1,{type:'play',index:0,stackTarget:g.stack[0].uid});passes(g);assert.equal(g.stack.length,0);assert.equal(g.players[0].board.length,0);assert.deepEqual(g.players[0].grave,['guard']);
g=fresh();const knight=make('knight'),bone=make('bone');g.players[0].board=[knight];g.players[1].board=[bone];g.phase='attackers';act(g,0,{type:'attackers',attackers:[knight.uid]});passes(g);act(g,1,{type:'blockers',blocks:{[knight.uid]:[bone.uid]}});passes(g);assert.equal(g.players[0].board[0].damage,0);assert.equal(g.players[1].board.length,0);assert.equal(g.players[1].hp,20);
g=fresh();const ogre=make('ogre'),b1=make('bone'),b2=make('bone');g.players[0].board=[ogre];g.players[1].board=[b1,b2];g.phase='attackers';act(g,0,{type:'attackers',attackers:[ogre.uid]});passes(g);act(g,1,{type:'blockers',blocks:{[ogre.uid]:[b1.uid,b2.uid]}});passes(g);assert.equal(g.players[1].hp,17);assert.equal(g.players[0].board[0].damage,4);
g=fresh();const w=make('wolf'),b=make('bone');g.players[0].board=[w];g.players[1].board=[b];g.phase='attackers';act(g,0,{type:'attackers',attackers:[w.uid]});passes(g);act(g,1,{type:'blockers',blocks:{[w.uid]:[b.uid]}});g.players[1].board=[];passes(g);assert.equal(g.players[1].hp,20);
g=fresh();const shade=make('shade'),guard=make('guard');g.players[0].board=[shade];g.players[1].board=[guard];g.phase='attackers';act(g,0,{type:'attackers',attackers:[shade.uid]});passes(g);assert.throws(()=>act(g,1,{type:'blockers',blocks:{[shade.uid]:[guard.uid]}}));
g=fresh();g.phase='attackers';g.players[0].board=[make('guard',{sick:true})];assert.throws(()=>act(g,0,{type:'attackers',attackers:[g.players[0].board[0].uid]}));
g=fresh();g.players[0].board=[make('blade'),make('guard')];g.players[0].lands=[make('plains'),make('plains')];act(g,0,{type:'equip',uid:g.players[0].board[0].uid,target:{player:0,uid:g.players[0].board[1].uid}});passes(g);assert.deepEqual(stats(g,0,g.players[0].board[1]),{power:3,toughness:3});
g=fresh();g.phase='end';g.players[1].deck=[];passes(g);assert.equal(g.winner,0);
// A deterministic decision policy exercises full games without bypassing priority.
for(let n=0;n<20;n++){g=newGame(n%2?'Warrior':'Necromancer');let steps=0;while(g.winner===null&&steps++<1800){ai(g);if(g.winner!==null)break;const p=g.players[0],e=g.players[1];if(g.phase==='attackers'){assert.equal(g.turn,0);act(g,0,{type:'attackers',attackers:p.board.filter(u=>card(u.id).type==='Creature'&&!u.sick&&!u.tapped).map(u=>u.uid)});continue;}if(g.phase==='blockers'){assert.equal(g.turn,1);act(g,0,{type:'blockers',blocks:{}});continue;}assert.equal(g.priority,0);let played=false;for(let i=0;i<p.hand.length;i++){const c=card(p.hand[i]);let target,stackTarget;if(c.effect==='counter'){const x=g.stack.find(s=>s.owner===1&&!s.equip);if(!x)continue;stackTarget=x.uid;}else if(c.effect==='bolt')target={player:1};else if(c.effect==='pump'){const u=p.board.find(u=>card(u.id).type==='Creature');if(!u)continue;target={player:0,uid:u.uid};}else if(c.effect==='smite'){const u=e.board.find(u=>card(u.id).type==='Creature');if(!u)continue;target={player:1,uid:u.uid};}try{act(g,0,{type:'play',index:i,target,stackTarget});played=true;break;}catch{}}
if(!played)act(g,0,{type:'pass'});for(const p of g.players){assert.ok(p.pool.W>=0&&p.pool.B>=0);assert.ok(p.board.every(u=>u.damage<stats(g,g.players.indexOf(p),u).toughness||card(u.id).type!=='Creature'));}}
assert.notEqual(g.winner,null,'Game stalled');}
assert.equal(starter('Warrior').length,40);assert.equal(starter('Necromancer').length,40);
console.log('10 targeted rules scenarios and 20 complete duels passed.');
