'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Card,card,colors,divisions,clanColor,Rarity,rarityNames} from '@/lib/game';
import {packRules} from '@/lib/packs';
type Receipt={id:string,tier:string,cards:string[],openedAt:number};
type Vault={starterClan:string|null,unopened:{id:string,tier:string}[],history:Receipt[]};
export function EqMark({rarity}:{rarity:Rarity}){return <span className={'eqMark rarity-'+rarity} title={rarityNames[rarity]} aria-label={'EQ — '+rarityNames[rarity]}>EQ</span>}
export default function PackVault({vault,busy,send,renderCard,onStarter}:{vault:Vault|undefined,busy:boolean,send:(b:any)=>Promise<any>,renderCard:(c:Card)=>React.ReactNode,onStarter:(clan:string)=>void}){
const [dialog,setDialog]=useState(false),[opening,setOpening]=useState(false),[receipt,setReceipt]=useState<Receipt|null>(null),[revealed,setRevealed]=useState<number[]>([]),[problem,setProblem]=useState('');
async function open(id:string){if(busy||opening)return;setProblem('');setReceipt(null);setRevealed([]);setDialog(true);setOpening(true);const start=Date.now();try{let d=await send({type:'open_pack',id});if(!d)d=await send({type:'load'});const opened=d?.openedPack||d?.packs?.history?.find((r:Receipt)=>r.id===id);if(!opened)throw Error('Opening could not be confirmed. Close this window and reload; any completed opening is saved in Pack history.');await new Promise(r=>setTimeout(r,Math.max(0,1000-(Date.now()-start))));setReceipt(opened);}catch(e){setProblem((e as Error).message);}finally{setOpening(false);}}
function replay(r:Receipt){setProblem('');setReceipt(r);setRevealed([]);setDialog(true);}
const tiers:Rarity[]=['common','uncommon','rare','mythical'];const remaining=vault?.unopened.length||0;
return <section className="packVault panel"><div className="vaultHead"><div><small>THE VAULT OF NORRATH</small><h2>Unseal your next legend.</h2><p>10 cards per pack. Rarity belongs to the cards.</p></div><div className="packCounter"><strong>{remaining}</strong><span>unopened packs</span></div></div>
<div className="rarityLegend">{tiers.map(r=><span key={r}><EqMark rarity={r}/>{rarityNames[r]}</span>)}</div>
{!vault?.starterClan?<section className="starterGift"><div><small>YOUR FREE STARTER DECK</small><h3>Choose your first allegiance.</h3><p>One complete 40-card deck: 16 basic lands and 24 common/uncommon cards. Basic lands are always free.</p></div><div className="starterChoices">{colors.map(color=>divisions[color].clan).map(clan=><button key={clan} disabled={busy||!vault} onClick={async()=>{const d=await send({type:'claim_starter',clan});if(d){onStarter(clan);}}}><strong>{clan}</strong><span>{divisions[clanColor(clan)].name+' · '+divisions[clanColor(clan)].title}</span><small>Claim free deck</small></button>)}</div></section>:<p className="starterClaimed">✓ {vault.starterClan} starter deck claimed · Your collection and opened cards are saved to your account.</p>}
<div className="welcomeBundle"><strong>Your 10 free welcome packs</strong><span>10 identical packs · Granted once per account</span></div>
<div className="packShelf"><article className="packOffer"><div className="packArt packArt0" role="img" aria-label="EQ Tavern Duels card pack"/><div className="packOfferTitle"><h3>Tavern Duels card pack</h3><span>×{remaining}</span></div><p>{packRules.description}</p><button className="gold" disabled={busy||opening||!remaining} onClick={()=>open(vault!.unopened[0].id)}>{remaining?'Open pack':'No packs available'}</button></article></div>
<p className="packNotes">Cards are drawn from all five color divisions. Duplicates are possible and become additional tradable copies. Basic lands are not included in packs. Every card within the same rarity has an equal chance of appearing.</p>
<section className="packHistory"><h3>Pack history</h3><p>Revisit an opening at any time. Viewing it again never spends another pack.</p>{!vault?.history.length?<div className="empty">Your first opening will appear here.</div>:<div className="historyList">{vault.history.map(r=><button key={r.id} onClick={()=>replay(r)}><span className="historyPackIcon" aria-hidden="true">EQ</span><span><strong>Card pack</strong><small>{new Date(r.openedAt).toLocaleDateString()} · {r.cards.length} cards saved</small></span><span className="historyRarities">{r.cards.map((id,i)=><EqMark key={i} rarity={card(id).rarity}/>)}</span><span>View cards</span></button>)}</div>}</section>
<Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="packOpening"><DialogTitle>{opening?'Breaking the seal…':receipt?'Your cards await.':'Pack opening'}</DialogTitle><DialogDescription>{opening?'Your pack is being opened and saved.':receipt?`${receipt.cards.length} cards are already in your collection.`:problem}</DialogDescription>
{opening?<div className="unsealScene"><div className="packArt openingPack packArt0"/><div className="sealLight"/><p>Unsealing your pack</p></div>:receipt?<><div className="revealGrid">{receipt.cards.map((id,i)=>{const c=card(id),isRevealed=revealed.includes(i);return <div key={receipt.id+':'+i} className={'revealSlot '+(isRevealed?'revealed rarity-'+c.rarity:'sealed')}>
{isRevealed?<div className="revealedFace">{renderCard(c)}<span className={'revealRarity rarity-'+c.rarity}>{rarityNames[c.rarity]}</span></div>:<button className="cardBack" aria-label={`Reveal card ${i+1} of ${receipt.cards.length}`} onClick={()=>setRevealed(old=>[...old,i])}><span className="backMonogram">EQ</span><span>TAVERN DUELS</span><small>Tap to reveal</small></button>}</div>})}</div><div className="revealActions"><span aria-live="polite">{revealed.length} / {receipt.cards.length} revealed</span>{revealed.length<receipt.cards.length?<button className="gold" onClick={()=>setRevealed(receipt.cards.map((_,i)=>i))}>Reveal all</button>:<button className="gold" onClick={()=>setDialog(false)}>Back to packs</button>}</div></>:<p role="alert">{problem||'You can safely close this window and try again.'}</p>}
</DialogContent></Dialog>
</section>;
}
